### ISSUE TITLE
Add CI action to test PRs to this repo

### ISSUE THREAD

**Issue by axel-h** [seL4/sel4bench#15]
Add CI action to test PRs to this repo.

**Comment by lsf37** [comment]
The only tests for sel4bench are hardware tests so far, which I don't think we should run automatically on every PR.

We could enable the builds for those tests, though, and make the tests themselves  available to be triggered via a label, though. That would certainly be an improvement.

Would it make sense to have something under simulation that doesn't measure anything useful but that confirms that the code at least runs and does not just compile?

**Comment by axel-h** [comment]
I think this makes sense on a practical level, seeing that it builds and runs into know issues is worth something at least. I've seen that some tests fail in QEMU due to some jitter getting detected, so it's triggering a sanity check at least that get some test coverage then. Weighting this again more pressing issues it, might be a thing for the student task list.
I have an item on the lower end of my ToDo-List for running benchmarks in a simulation and either finding things that make sense, or find a simulation besides the standard QEMU (Renode, ARM FastModel .....) that is suitable enough to produce some stable numbers that are worth something. It came in though taking over https://github.com/seL4/seL4/pull/298 ...

**Comment by lsf37** [comment]
#19 adds sel4bench builds for pull requests and a `hw-test` label to run them on hardware. We should probably make simulation runs for sel4bench a separate issue, because that's a longer-term project.
