### ISSUE TITLE
Page-Mapping benchmark error "seL4_Fault_CapFault"

### ISSUE THREAD

**Issue by jingjin666** [seL4/sel4bench#29]
Test benchmark with page-mapping module on qemu-arm-virt platform.
error logs：

crash at：
`benchmark_spawn_process`

Caught cap fault in send phase at address 0
while trying to handle:
vm fault on data at address 0x46cde0 with status 0x92000007
in thread 0xffffff806ffde400 "Proc" at address 0x45598c
With stack:
0x10011d60: 0x0
0x10011d68: 0x0
0x10011d70: 0x10011e70
0x10011d78: 0x10011e70
0x10011d80: 0x0
0x10011d88: 0x0
0x10011d90: 0x10011e70
0x10011d98: 0x10011e70
0x10011da0: 0x10011e30
0x10011da8: 0xffffff80ffffffc8
0x10011db0: 0x0
0x10011db8: 0x0
0x10011dc0: 0x0
0x10011dc8: 0x0
0x10011dd0: 0x0
0x10011dd8: 0x0

**Comment by Ivan-Velickovic** [comment]
Hi, could you provide the command use to build the benchmark? Also, was this using the latest sel4bench manifest?

**Comment by jingjin666** [comment]
@Ivan-Velickovic The problem is missed with build by configure as -DRELEASE=TRUE
