### ISSUE TITLE
Question about benchmark results

### ISSUE THREAD

**Issue by ChenYangng** [seL4/sel4bench#41]
Chapter 6 of the seL4 white paper states that the overhead of a round-trip IPC is approximately 720 cycles.
Up-to-date performance results  listed on the  [seL4 Benchmarks page] (https://sel4.systems/About/Performance/) look much better, 382cycles for a IPC call on i7-6700/Skylake.I wonder why.

**Comment by gernotheiser** [comment]
Call is only one side of an IPC. A round-trip is Call+Reply, which at the moment is 383+389=772 cycles.
